# Generated by Django 5.2.6 on 2025-09-10 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquantity',
            name='catalog',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcatalog'),
        ),
    ]
